server:
  port: 8080
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      cors-configurations:
        '[/**]':
         allowedOrigins: "http://localhost:3000"
         allowedMethods:
          - GET
          - POST
         allowedHeaders:
          - Content-Type
      discovery:
        locator:
          enabled: true
      routes:
        - id: msv-users
          uri: lb://msv-users
          predicates:
            - Path=/api/users/**
          filters:
            - AuthFilter
        - id: msv-order
          uri: lb://msv-order
          predicates:
            - Path=/api/orders/**
        - id: msv-products
          uri: lb://msv-products
          predicates:
            - Path=/api/products/**
        - id: auth-server
          uri: lb://auth-server
          predicates:
            - Path=/api/auth/**